import zipfile, os

TODAY = "2026-06-03"
PACK_TXT = f"packs/{TODAY}-CLAUDE_AUTO_PACK.txt"
PACK_ZIP = f"packs/{TODAY}-CLAUDE_AUTO_PACK.zip"

ENTRIES = [
    ("en_ftr_intel","2026-06-02 12:00:00","STB Accepts UPNS Merger Application — But the Clock May Be Slowing Down ","The Surface Transportation Board has accepted UPNS merger application for consideration but analysts note regulatory momentum may be slowing as shipper opposition mounts. The proposed union would combine two Class I railroads serving overlapping Midwest and Gulf Coast corridors."),
    ("en_ftr_intel","2026-06-01 12:00:00","The Economic Tug-of-War Behind Today's Freight Market ","FTR Intelligence examines competing macro forces shaping freight demand: tariff-driven front-loading has pulled forward industrial volumes while housing weakness and consumer caution suppress retail freight. Carriers are navigating a two-speed economy with divergent lane dynamics."),
    ("en_ftr_intel","2026-05-29 12:00:00","Spot Rates Keep Climbing as Capacity Tightens ","Dry van spot rates continued their upward trajectory in the week ending May 29 as available truckload capacity tightened. FTR data shows load-to-truck ratios climbing across major lanes, suggesting the rate environment may support further increases heading into summer."),
    ("en_the_quantum_insider","2026-05-31 12:00:00","French National Quantum Update: May 2026 ","France’s national quantum program released its May update highlighting progress at CEA and Institut Quantique. Key milestones include new qubit coherence records at a Paris laboratory and expanded industry partnerships with Thales and Atos for quantum-classical hybrid computing."),
    ("en_the_quantum_insider","2026-05-28 12:00:00","IBM Plans $10 Billion Quantum Push as Efforts to Commercialize Quantum Intensifies ","IBM announced a $10 billion multi-year investment to accelerate quantum computing commercialization, targeting fault-tolerant systems by 2029. The plan includes expanding the IBM Quantum Network and launching new cloud-based quantum services for financial modeling and drug discovery applications."),
    ("en_the_quantum_insider","2026-05-26 12:00:00","Honeywell-Backed Quantinuum Files for Landmark Quantum IPO ","Quantinuum, majority-owned by Honeywell, has filed for an initial public offering that would mark the first major pure-play quantum computing company to list on a US exchange. The company reported growing enterprise revenue from its H-Series trapped-ion hardware and InQuanto chemistry platform."),
    ("en_smart_water_mag","2026-06-01 12:00:00","Spanish Emirati consortium secures $285 million Fujairah desalination contract ","A consortium led by Acciona and Mubadala has been awarded a $285 million contract to expand the Fujairah II independent water and power project in the UAE. The expansion will add 150 million gallons per day of desalination capacity using advanced reverse osmosis technology."),
    ("en_smart_water_mag","2026-05-27 12:00:00","EU opens consultation on digitalising water management and smart meter rollout ","The European Commission launched a public consultation on mandating smart water meters across member states as part of the revised Urban Wastewater Treatment Directive. The consultation examines interoperability standards, data privacy frameworks, and deployment timelines for utilities."),
    ("en_smart_water_mag","2026-05-20 12:00:00","Unsafe drinking water: mirror and magnifier of inequality in developing nations, finds UN report ","A new UN-Water report finds that 2.2 billion people still lack safely managed drinking water, with access gaps concentrated in sub-Saharan Africa and South Asia. The report calls for tripling climate finance for water infrastructure and prioritizing sanitation in national adaptation plans."),
    ("en_global_taiwan","2026-05-26 12:00:00","China’s Next Target in the South China Sea: Taiwan? ","The Global Taiwan Institute analyzes whether China’s increased assertiveness in the South China Sea represents a strategic rehearsal for pressure against Taiwan. The piece examines PLAAF incursion patterns, coast guard deployments, and US freedom-of-navigation operations as indicators."),
    ("en_global_taiwan","2026-05-20 12:00:00","How Taiwan Fared during the 2026 Trump-Xi Summit ","Analysis of outcomes from the Trump-Xi summit for Taiwan’s strategic interests. The piece examines whether US commitments on arms sales, semiconductor trade restrictions, and the Taiwan Relations Act were weakened or maintained during bilateral negotiations."),
    ("en_global_taiwan","2026-05-15 12:00:00","Why Taiwan’s 2026 Local Elections Will be Key to PRC Cognitive Warfare Strategy ","Taiwan’s upcoming local elections present an opportunity for PRC influence operations targeting municipal candidates and local media. The analysis details documented cases of disinformation seeding, funding networks, and social media amplification targeting specific competitive districts."),
    ("en_nrf","2026-05-13 12:00:00","Loss Prevention and Asset Protection Leaders to be Honored at NRF PROTECT 2026 ","The National Retail Federation announced honorees for the LP Magazine Retail Crime Fighter Award and Ring of Excellence at NRF PROTECT 2026. Winners were recognized for innovations in AI-powered surveillance, organized retail crime disruption, and cross-industry data sharing programs."),
    ("en_nrf","2026-05-12 12:00:00","NRF Commends House Passage of Federal Retail Crime Bill ","The National Retail Federation praised the House for passing the INFORM Consumers Act updates targeting organized retail crime networks. The legislation expands online marketplace seller verification requirements and increases penalties for interstate theft rings exceeding $5,000 in value."),
    ("en_nrf","2026-05-08 12:00:00","Import Cargo Volume Expected to See Year-Over-Year Drop During First Half of 2026 ","NRF and Hackett Associates Global Port Tracker forecasts US import cargo volumes will decline approximately 8% year-over-year in H1 2026 as tariff front-loading from late 2025 unwinds. West Coast ports are projected to bear the brunt of the correction through June."),
    ("en_reinsurance_news","2026-06-01 12:00:00","26North Re to acquire Independent Insurance Group in strategic entry into US insurance market ","26North Re, the reinsurance arm of 26North Partners, announced an agreement to acquire Independent Insurance Group as its platform entry into the US primary insurance market. The deal expands 26North’s underwriting capacity across commercial lines and specialty property risks."),
    ("en_reinsurance_news","2026-05-29 12:00:00","MassMutual and Nationwide enter strategic reinsurance agreement ","MassMutual and Nationwide Financial announced a block reinsurance transaction covering approximately $8 billion in life insurance reserves. The deal allows Nationwide to free regulatory capital for growth while MassMutual gains long-duration liability exposure aligned with its investment portfolio."),
    ("en_reinsurance_news","2026-05-29 12:00:00","Liberty Mutual launches carrier-backed conversational AI auto insurance quoting app in ChatGPT ","Liberty Mutual introduced a ChatGPT plugin enabling consumers to receive real-time auto insurance quotes through conversational AI. The integration uses Liberty’s rating engine APIs and marks one of the first carrier-direct AI quoting deployments in the personal lines market."),
    ("cn_guancha","2026-05-31 12:00:00","12至18个月内全球或将爆发金融危机？怎么看高志凯老师的预警 ","观察者网探讨学者高志凯关于全球可能在12至18个月内爆发金融危机的预警。文章分析美联储政策、美债压力、美元信用等因素，探讨危机传导路径及中国应对策略。"),
    ("cn_guancha","2026-05-20 12:00:00","科创50指数涨超3%再创新高，半导体大涨，兆易创新、盛景微涨停 ","科创50指数单日涨幅超过3%，再创历史新高，半导体板块领涨。兆易创新、盛景微等芯片设计企业涨停，市场情绪受国产替代加速和AI算力需求提振。"),
    ("cn_guancha","2026-05-07 12:00:00","冲刺头部大模型遇挫，马斯克解散xAI转战云服务 ","据报道马斯克旗下xAI在大模型竞争中遭遇挫折后，正将业务重心转向云基础设施服务。观察者网分析这一战略转变对AI产业格局的影响及与OpenAI、Anthropic等竞争态势。"),
    ("en_risk_and_insurance","2026-05-26 12:00:00","A Look at How Real Estate Insurers Are Responding to Climate Change ","Property insurers serving the commercial real estate sector are deploying catastrophe models with higher resolution climate projections to reprice coastal and wildfire-exposed assets. Several carriers have exited California and Florida markets entirely while others are conditioning coverage on risk mitigation investments."),
    ("en_risk_and_insurance","2026-05-22 12:00:00","P&C Industry Posts Record First-Quarter Underwriting Profit, Extending Profitable Streak ","The US property-casualty industry reported record underwriting income in Q1 2026, with the combined ratio falling to 92.4%. Rate adequacy achieved over the past three years, reduced catastrophe losses, and improved reserve positions drove the outperformance across commercial lines."),
    ("en_risk_and_insurance","2026-05-20 12:00:00","The Broker’s Many Hats: Meet the 2026 Rising Stars ","Risk & Insurance recognized its annual Rising Stars in insurance brokerage, highlighting professionals who have driven innovation in parametric risk transfer, captive formation, and AI-assisted exposure analysis. Honorees represent firms including Marsh, Aon, WTW, and independent regional brokers."),
    ("en_trucking_dive","2026-06-01 12:00:00","FedEx Freight now an independent company ","FedEx Freight officially became an independent publicly traded company following the completion of its spin-off from FedEx Corp. The less-than-truckload carrier, renamed FedEx Freight Inc., began trading on the NYSE and outlined a standalone capital allocation strategy focused on network density and terminal expansion."),
    ("en_trucking_dive","2026-05-19 12:00:00","FMCSA to expand Motus registration overhaul in Q2 ","The Federal Motor Carrier Safety Administration announced it will expand the Motus carrier registration system to additional states in Q2 2026 as part of a phased national rollout. The system replaces legacy MCMIS infrastructure and introduces real-time compliance data integration with state DMVs."),
    ("en_trucking_dive","2026-05-06 12:00:00","Aurora Innovation, McLane expanding partnership in Texas ","Aurora Innovation and McLane Company announced an expanded autonomous trucking partnership covering additional Texas lanes between distribution centers and retail delivery points. Aurora’s driverless trucks have now completed over 1,200 commercial deliveries under the partnership since its 2025 launch."),
    ("en_healthcare_it_today","2026-05-31 12:00:00","Bonus Features – May 31, 2026 – 1 in 8 medical practices have deployed an AI receptionist ","Healthcare IT Today’s weekly roundup notes a MGMA survey finding one in eight medical practices has deployed an AI-powered virtual receptionist. Other items cover Epic’s expanded ambient AI documentation rollout, CMS interoperability rule enforcement updates, and a health system CISO survey on ransomware preparedness."),
    ("en_healthcare_it_today","2026-05-30 12:00:00","Weekly Roundup – May 30, 2026 ","This week’s healthcare IT news roundup covers Oracle Health’s federal EHR contract renewal, AWS HealthLake new FHIR R4 analytics features, payer-provider API mandate enforcement actions, and a review of ambient AI scribing adoption rates across health system size segments."),
    ("en_healthcare_it_today","2026-05-18 12:00:00","HealthVerity Completes Acquisition of Symphony Health, Marking a New Era for the Healthcare Data Industry ","HealthVerity finalized its acquisition of Symphony Health from PRA Group, creating one of the largest healthcare data platforms in the US. The combined entity links pharmacy, medical claims, and patient-level longitudinal data for life sciences market access, outcomes research, and commercial analytics."),
    ("en_infrastructure_investor","2026-05-15 12:00:00","GIP targets $10bn for new GCC, Central Asia fund ","Global Infrastructure Partners is raising a $10 billion dedicated fund targeting infrastructure assets across Gulf Cooperation Council countries and Central Asia. The strategy focuses on energy transition, digital infrastructure, and logistics assets in markets with sovereign wealth fund co-investment potential."),
    ("en_infrastructure_investor","2026-05-14 12:00:00","Snowhawk exceeds target to close debut digital fund on $1.3bn ","Snowhawk Capital closed its inaugural digital infrastructure fund at $1.3 billion, exceeding its $1 billion target on strong LP demand for data centers and fiber networks. The fund will deploy primarily in North America and Western Europe with a focus on hyperscaler-anchored assets."),
    ("en_infrastructure_investor","2026-05-12 12:00:00","Taaleri launches €1bn fourth renewables fund ","Finnish asset manager Taaleri launched its fourth renewable energy fund targeting €1 billion in commitments for wind and solar projects across the Nordic and Baltic regions. The fund will co-invest alongside Taaleri’s balance sheet and Nordic institutional LPs in projects with power purchase agreements."),
    ("en_top1000funds","2026-06-02 12:00:00","AustralianSuper names Shaun Manuell as new chief investment officer ","AustralianSuper, Australia’s largest superannuation fund with over A$360 billion in assets, appointed Shaun Manuell as its new CIO. Manuell, previously deputy CIO, will oversee the fund’s global asset allocation strategy including its expanding international private markets program."),
    ("en_top1000funds","2026-06-01 12:00:00","Utah Retirement System CIO charts next-generation nuclear energy investment thesis ","Utah Retirement System’s CIO outlined a thesis for investing in next-generation nuclear energy through a combination of listed utilities, private project equity, and venture positions in small modular reactor developers. The fund sees nuclear as essential for both energy security and portfolio decarbonization."),
    ("en_top1000funds","2026-05-18 12:00:00","Funds SA cuts active risk as CIO puts stable beta first ","South Australia’s Funds SA reduced active management risk across its $50 billion portfolio as its new CIO repositioned toward factor-based and passive exposures. The shift reflects concerns about active manager alpha persistence in late-cycle equity markets and aims to reduce fee drag."),
    ("en_coverager","2026-05-27 12:00:00","American Family files trademark for ‘EV Claims Advantage’ ","American Family Insurance filed a USPTO trademark application for “EV Claims Advantage,” signaling the carrier is developing a specialized electric vehicle claims handling product. The filing suggests a dedicated workflow for battery damage assessment, charging infrastructure claims, and OEM repair network coordination."),
    ("en_coverager","2026-05-21 12:00:00","Farmers files trademark for ‘Coverage on a Page’ ","Farmers Insurance filed for the trademark “Coverage on a Page,” indicating development of a simplified policy summary product. The initiative aligns with industry-wide efforts to improve policyholder comprehension of coverage terms and reduce disputes over claim denials tied to policy misunderstanding."),
    ("en_coverager","2026-05-19 12:00:00","InsurGrid Expands AI-Powered Policy Extraction and Comparison for P&C Agents ","InsurGrid announced expansion of its AI platform that automatically extracts coverage data from uploaded policy documents and benchmarks terms against carrier databases. The tool enables agents to identify coverage gaps and provide comparative analysis during the renewal and cross-sell process."),
    ("en_alcircle","2026-06-03 12:00:00","Australia extends anti-dumping duties on Malaysian aluminium extrusions after review ","Australia’s Anti-Dumping Commission confirmed the extension of anti-dumping and countervailing duties on aluminium extrusions from Malaysia following a sunset review. Duties ranging from 4.5% to 57.4% will remain in place, protecting domestic producers from below-cost imports."),
    ("en_alcircle","2026-05-06 12:00:00","G7 focuses on aluminium and other critical minerals as US-EU tariff tensions test unity ","G7 trade ministers discussed coordinated aluminium and critical minerals policy at their May meeting, with the US Section 232 tariffs straining alliance cohesion. The communiqué called for joint supply chain mapping but stopped short of a unified tariff response framework."),
    ("en_alcircle","2026-05-01 12:00:00","Vedanta demerger completes, aluminium metal operations launch as standalone unit ","Vedanta Limited completed its demerger into six independent listed entities, with Vedanta Aluminium launching as a standalone company on Indian exchanges. The aluminium unit, which operates the Jharsuguda smelter and Lanjigarh refinery, immediately joined benchmark indices and outlined a capacity expansion roadmap."),
    ("en_wealth_management","2026-06-02 12:00:00","13 Investment Must Reads for This Week (June 2, 2026) ","WealthManagement.com’s curated reading list covers Fed rate path debate, private credit default rate trends, RIA M&A deal pace in Q2, alternative asset democratization through interval funds, and BlackRock’s latest capital markets assumptions update."),
    ("en_wealth_management","2026-05-26 12:00:00","16 Investment Must Reads (May 26, 2026) ","This week’s investment reading list features analysis of the inverted yield curve’s persistence, UHNW family office allocation shifts toward real assets, municipal bond credit quality amid state fiscal stress, and the outlook for international developed market equities relative to US."),
    ("en_wealth_management","2026-05-20 12:00:00","AllianceBernstein, Brookfield, Carlyle Team Up on Private Markets Push for DC Plans ","AllianceBernstein, Brookfield Asset Management, and Carlyle announced a consortium to develop a private markets target-date fund series for defined contribution retirement plans. The structure uses a daily-valued, liquid wrapper to give 401(k) participants access to private equity, private credit, and infrastructure."),
    ("en_hfma","2026-05-21 12:00:00","CMS’s Medicaid state-directed payment rule would expand limits beyond hospitals ","The Healthcare Financial Management Association analyzes CMS’s proposed rule that would extend Medicaid state-directed payment methodologies to non-hospital provider types including physician groups and community health centers. The rule could significantly expand supplemental payments in states with robust managed care programs."),
    ("en_hfma","2026-05-20 12:00:00","Growth projects lead amid reduced hospital capex ","HFMA survey data shows hospital capital expenditure declined 12% year-over-year in Q1 2026, with growth-oriented projects such as ambulatory care centers and outpatient surgery centers capturing a larger share of reduced budgets. Deferred maintenance and IT infrastructure spending saw the steepest cuts."),
    ("en_hfma","2026-05-15 12:00:00","Finalized regulations look to phase out the manual aspect of prior authorization ","HFMA reviews CMS’s final rule on prior authorization automation, which requires payers to implement FHIR-based APIs for electronic prior authorization by 2027. The rule is projected to save the healthcare system $15 billion annually by reducing administrative burden on providers and payers."),
    ("en_ai_cio","2026-06-01 12:00:00","CPP Investments’ 7.8% Fiscal 2026 Return Buoyed by IT, Communications Sectors ","The Canada Pension Plan Investment Board reported a 7.8% net return for fiscal year 2026, with information technology and communications holdings driving outperformance. The fund’s net assets reached C$714 billion, supported by strong private equity distributions and infrastructure income."),
    ("en_ai_cio","2026-05-28 12:00:00","Monte Tarbox Brings Diversified Approach to NYC Pensions’ Investments ","New York City’s pension system CIO Monte Tarbox outlined a portfolio diversification strategy emphasizing non-correlated alternatives, including infrastructure debt, reinsurance-linked securities, and private credit. The NYC systems collectively manage over $280 billion in assets for municipal workers."),
    ("en_ai_cio","2026-05-22 12:00:00","Corporate Pension Plans Inch Further Into Surplus Territory ","Mercer data shows corporate defined benefit plans in the US reached an aggregate funded status of 108% in May 2026, the highest level since 2007. Rising discount rates and strong equity returns have prompted many plan sponsors to accelerate liability-driven investing and annuity buyout strategies."),
    ("en_commercial_search","2026-06-01 12:00:00","The June Digital Issue of CPE Is Now Available! ","Commercial Property Executive’s June 2026 digital issue features a cover story on industrial outdoor storage as an emerging CRE asset class, plus analysis of life science lab vacancy trends, multifamily cap rate compression in Sun Belt markets, and data center REIT performance."),
    ("en_commercial_search","2026-05-25 12:00:00","CRE People on the Move (Week of May 25, 2026) ","This week’s commercial real estate executive moves include CBRE appointing a new head of data center advisory, JLL naming a regional industrial lead for the Southeast, and several senior broker transitions between Cushman & Wakefield and Newmark in major gateway markets."),
    ("en_commercial_search","2026-05-05 12:00:00","2026 Commercial REIT Values: Industrial Leads with Highest AFFO Payout Ratios ","CommercialSearch analysis finds industrial REITs post the highest adjusted funds from operations payout ratios among commercial real estate sectors in 2026, reflecting robust rent growth and low vacancy. Office REITs continue to trade at the steepest discounts to NAV across the sector."),
    ("en_crispr_medicine_news","2026-05-21 12:00:00","FDA Clears First-Ever In Vivo Gene-Editing Trial for Chronic Hepatitis B in the United States ","The FDA granted investigational new drug clearance for the first US clinical trial of an in vivo CRISPR gene-editing therapy targeting chronic hepatitis B. The therapy, developed by Excision BioTherapeutics, aims to excise integrated HBV DNA from infected hepatocytes using a single intravenous infusion."),
    ("en_crispr_medicine_news","2026-05-20 12:00:00","eGenesis Receives FDA Clearance for Gene-Edited Pig Kidney Trial in End-Stage Kidney Disease Patients ","eGenesis received FDA clearance to begin a clinical trial transplanting gene-edited pig kidneys into end-stage kidney disease patients who are not candidates for human donor organs. The pigs have 69 genomic edits removing harmful pig genes and inserting human compatibility factors."),
    ("en_crispr_medicine_news","2026-05-13 12:00:00","Off-the-shelf CRISPR CAR-T tackles brain tumours ","Researchers published Phase I data showing an allogeneic CRISPR-edited CAR-T cell therapy produced measurable responses in recurrent glioblastoma patients. The off-the-shelf approach uses donor T-cells with HLA genes knocked out to reduce rejection risk, potentially enabling wider access than autologous therapies."),
    ("en_trains","2026-05-29 12:00:00","What happened in the rail industry this week? May 29, 2026 ","Trains Magazine’s weekly rail roundup covers progress on the UPNS merger review, Amtrak’s ridership record in April, Class I capital spending updates for Q1 2026, and new federal infrastructure grants for short line railroad bridge rehabilitation projects."),
    ("en_trains","2026-05-22 12:00:00","What happened in the rail industry this week? May 22, 2026 ","This week in rail: BNSF announces expansion of its Bakken crude oil unit train network, positive train control system coverage reaches 99.8% of required route miles, and the FRA proposes updated crew size rules for freight operations following a notice of proposed rulemaking."),
    ("en_trains","2026-05-15 12:00:00","What happened in the rail industry this week? May 15, 2026 ","Rail news for the week of May 15: Canadian Pacific Kansas City reports strong Q1 intermodal volume growth, the STB opens comment period on competitive switching proposals, and California High-Speed Rail Authority releases updated ridership projections for the Merced-Bakersfield segment."),
    ("en_carbon_pulse","2026-05-29 12:00:00","CP Daily Newsletter: Friday May 29, 2026 ","Carbon Pulse’s daily newsletter covers EU ETS allowance prices retreating below €70 amid weaker industrial demand signals, California carbon auction results showing strong clearing prices, and new voluntary carbon standard updates from Verra affecting avoided deforestation credits."),
    ("en_carbon_pulse","2026-05-17 12:00:00","Voluntary Carbon Market News: May 11-17 2026 ","The week in voluntary carbon markets saw ICVCM approve four new carbon-crediting methodologies under the Core Carbon Principles framework, Microsoft announce a 10 million tonne forward purchase of direct air capture credits, and ongoing debate over the integrity of cookstove emission reduction projects."),
    ("en_carbon_pulse","2026-05-06 12:00:00","CP Daily Newsletter: Wednesday May 6, 2026 ","Carbon Pulse reports on EU Carbon Border Adjustment Mechanism compliance filing deadlines approaching for steel and aluminum importers, UK ETS price divergence from EU ETS widening to a record gap, and new Article 6 bilateral agreement between Switzerland and Vanuatu."),
    ("en_world_fertilizer","2026-05-13 12:00:00","CF Industries reports on the company’s 1Q26 earnings ","CF Industries reported Q1 2026 net earnings of $312 million on strong ammonia and urea sales volumes. The company cited elevated natural gas costs in the UK but noted North American production benefited from low domestic gas prices. Management raised full-year volume guidance on robust agricultural demand."),
    ("en_world_fertilizer","2026-05-08 12:00:00","Loop Chemicals licenses ammonia technology from Sandia National Laboratories ","Loop Chemicals signed an exclusive licensing agreement for Sandia National Laboratories’ electrochemical ammonia synthesis process, which operates at ambient pressure and temperature. The technology could enable distributed, renewable-powered fertilizer production without the carbon intensity of the Haber-Bosch process."),
    ("en_world_fertilizer","2026-05-07 12:00:00","Food security in focus as fertilizer costs surge ","World Fertilizer Magazine examines the food security implications of rising nitrogen and phosphate fertilizer prices, driven by energy cost increases and supply chain disruptions from Eastern European conflict. The analysis highlights differential impacts on subsistence farmers in Africa versus large commercial operators in Brazil."),
    ("en_jiemian_global","2026-03-05 12:00:00","China sets 2026 GDP growth target at about 4.5%–5% ","China’s National People’s Congress set the official GDP growth target for 2026 at approximately 4.5% to 5%, acknowledging external headwinds from US tariffs while maintaining fiscal stimulus commitments. The government announced a budget deficit of 4% of GDP and expanded special bond issuance for infrastructure."),
    ("en_jiemian_global","2026-01-15 12:00:00","China to launch next-generation digital yuan framework in 2026, shifting it toward deposit-like money ","China’s central bank announced plans to evolve the digital yuan from its current e-CNY pilot structure toward a deposit-based model integrated with commercial bank systems. The redesign aims to address adoption barriers and position the digital yuan for cross-border settlement use cases."),
    ("en_jiemian_global","2026-01-10 12:00:00","China expands foreign investment incentives, revised catalogue to take effect in 2026 ","China released an updated Foreign Investment Access Negative List and encouraged investment catalogue expanding sectors open to foreign capital, including financial services, healthcare, and advanced manufacturing. The revisions took effect January 1, 2026 as part of efforts to attract foreign direct investment amid global supply chain restructuring."),
    ("en_agriland","2026-06-01 12:00:00","Farmers urged to complete 2026 NI Farm Census before June 30 deadline ","Northern Ireland’s Department of Agriculture has issued an urgent reminder to farmers to submit their 2026 agricultural census returns before the June 30 deadline. The census captures livestock numbers, crop areas, and land use data that informs EU and UK agricultural subsidy distribution and policy planning."),
    ("en_agriland","2026-05-29 12:00:00","Future of organic farming to be discussed at Bord Bia Bloom ","Bord Bia Bloom 2026 will feature dedicated programming on the future of organic agriculture in Ireland, including panel discussions with organic certification bodies, retailer buyers, and organic conversion grant recipients. Ireland’s organic farmland area has grown 18% since 2022 under the new Organic Farming Scheme."),
    ("en_agriland","2026-05-20 12:00:00","Global grain markets continue to strengthen amid Black Sea supply uncertainty ","Agriland reports on continued strength in global wheat and corn prices as Black Sea export uncertainty persists. Chicago Board of Trade wheat futures rose 3.2% in the week ending May 20, while European milling wheat followed suit. Analysts cite Ukrainian harvest disruption and Russian export tax increases."),
    ("en_cen","2026-05-20 12:00:00","US and European chemical companies expect Iran war profit surge ","Chemical & Engineering News reports chemical industry analysts are modeling potential profit surges for specialty chemical producers if Iranian petrochemical exports are disrupted by military conflict. Ethylene, methanol, and propylene spot markets showed volatility in May on supply risk premiums."),
    ("en_cen","2026-05-15 12:00:00","EPA move risks politicizing chemical risk assessments, ex-official says ","A former EPA Office of Chemical Safety director warns that proposed changes to the Toxic Substances Control Act risk assessment process could inject political considerations into scientific evaluations of industrial chemicals. The critique targets new data sufficiency standards that critics say could block regulatory action."),
    ("en_cen","2026-05-10 12:00:00","North American petrochemical makers face structural overcapacity as European plants shut ","C&EN examines the structural overcapacity challenge facing North American ethylene and polyethylene producers as European high-cost plants shut and Chinese capacity expands. US Gulf Coast producers retain feedstock cost advantages but face margin pressure as global supply growth outpaces demand."),
    ("en_energy_monitor","2026-05-01 12:00:00","An energy transition can help end our reliance on expensive fuel ","Energy Monitor argues that accelerating the energy transition offers the most reliable long-term hedge against fossil fuel price volatility, citing IEA data showing renewable levelized costs now below new-build gas in most markets. The piece calls for policy certainty over short-term subsidy debates."),
    ("en_energy_monitor","2026-04-29 12:00:00","Germany’s energy transition: Reform and uncertainty ","Analysis of Germany’s Energiewende at a crossroads: the new government’s rollback of some renewable targets and reinstatement of gas infrastructure investments has created regulatory uncertainty for developers. The piece examines grid congestion costs, capacity market design debates, and offshore wind auction results."),
    ("en_energy_monitor","2026-03-02 12:00:00","ENGIE to acquire UK Power Networks for $14.2bn ","French utility ENGIE announced a £11 billion ($14.2 billion) acquisition of UK Power Networks, the electricity distribution operator serving London and the South East. The deal gives ENGIE direct ownership of regulated network assets critical to the UK’s electric vehicle charging and heat pump rollout."),
    ("en_proactive_investors","2026-05-26 12:00:00","Montero Mining finalizes first-pass drill program at Elvira gold project ","Montero Mining and Exploration completed its inaugural drill program at the Elvira gold project in Chile’s Atacama region, with assay results pending. The company targeted structural zones identified by induced polarization surveys and aims to define an initial mineral resource estimate by year-end."),
    ("en_proactive_investors","2026-05-13 12:00:00","American Rare Earths launches feasibility drilling at Cowboy State Mine on Halleck Creek project ","American Rare Earths initiated feasibility-stage drilling at its Cowboy State Mine within the Halleck Creek rare earth project in Wyoming. The program will provide geotechnical and metallurgical data for a prefeasibility study targeting the project’s heavy rare earth-enriched zones."),
    ("en_proactive_investors","2026-05-10 12:00:00","Pan African Resources expects record annual gold production for fiscal year to June 2026 ","Pan African Resources issued a production guidance update projecting record gold output for its fiscal year ending June 2026, driven by strong performance at the Barberton Mines and Elikhulu tailings retreatment operation. The company flagged stable South African grid power as a key operational enabler."),
    ("en_biofuels_digest","2026-05-28 12:00:00","Montana Renewables receives $1.44B DOE guaranteed loan facility ","Montana Renewables secured a $1.44 billion DOE Loan Programs Office loan guarantee to finance the second phase of its Great Falls biorefinery expansion. The facility will process 30,000 barrels per day of used cooking oil and tallow into sustainable aviation fuel and renewable diesel."),
    ("en_biofuels_digest","2026-05-20 12:00:00","USDA, DOE announce $646M in advanced biofuels loan guarantees ","The USDA and DOE jointly announced $646 million in loan guarantees for advanced biofuel projects under the Inflation Reduction Act rural energy programs. Recipients include ethanol-to-SAF conversion projects in the Midwest and cellulosic biomass facilities in the Southeast."),
    ("en_biofuels_digest","2026-05-10 12:00:00","Bayer and bp announce long-term camelina alliance for sustainable aviation fuel ","Bayer and bp entered a multi-year agreement to develop camelina as a dedicated oilseed feedstock for sustainable aviation fuel. Bayer will supply improved camelina seed varieties under contract to bp-partnered farmers, with offtake agreements guaranteeing a floor price tied to SAF market benchmarks."),
    ("en_iot_analytics","2026-05-28 12:00:00","What CEOs talked about in Q1 2026: Iran war, physical/agentic AI, OpenClaw, and the SaaSpocalypse ","IoT Analytics analyzed 1,200 earnings call transcripts from Q1 2026, finding Iran conflict supply chain risk, agentic AI deployment, the OpenClaw robotics platform, and SaaS pricing pressure as the top themes. Industrial and logistics CEOs led mentions of physical AI and autonomous operations."),
    ("en_iot_analytics","2026-05-01 12:00:00","US manufacturing reshoring boom: What the data says one year after ‘Liberation Day’ tariffs ","One year after the April 2025 tariff announcements, IoT Analytics quantifies the US manufacturing reshoring impact: 340 new facility announcements, $280 billion in committed capital expenditure, but actual employment additions lagging projections due to automation-heavy greenfield designs."),
    ("en_iot_analytics","2026-04-15 12:00:00","7 most notable IoT and telco networking trends – as seen at MWC 2026 ","IoT Analytics reports from MWC 2026 on the seven most significant trends: 5G RedCap device proliferation, private network-as-a-service models, AI-native radio access networks, satellite-terrestrial integration, industrial metaverse pilots, energy-efficient edge computing, and GSMA Open Gateway API traction."),
]

ENTRIES_SORTED = sorted(ENTRIES, key=lambda x: x[1], reverse=True)

with open(PACK_TXT, 'w', encoding='utf-8') as f:
    for sql_name, dt, title, content in ENTRIES_SORTED:
        f.write(sql_name + "\n")
        f.write(dt + "\n")
        f.write(title + "\n")
        f.write(content + "\n")
        f.write("\n")
        f.write("-------------------------\n")

print(f"Written {len(ENTRIES_SORTED)} entries to {PACK_TXT}")

with zipfile.ZipFile(PACK_ZIP, 'w', zipfile.ZIP_DEFLATED) as zf:
    zf.write(PACK_TXT, arcname=f"{TODAY}-CLAUDE_AUTO_PACK.txt")

print(f"Zipped to {PACK_ZIP}")

new_sites = list(dict.fromkeys([e[0] for e in ENTRIES_SORTED]))
print(f"New sites ({len(new_sites)}): {new_sites}")

with open("packs/discovered_sites.txt", "a", encoding="utf-8") as f:
    for s in new_sites:
        f.write(s + "\n")

print("Appended to discovered_sites.txt")
